export const SEHIR_ILCE: Record<string, string[]> = {
  adana: ["seyhan", "yuregir", "cukurova", "sarıcam", "kozan", "ceyhan", "karaisali", "imamoglu", "pozanti", "saimbeyli", "tufanbeyli", "yumurtalik", "aladağ"],
  adiyaman: ["merkez", "besni", "celikhan", "gerger", "golbasi", "kahta", "samsat", "sincik", "tut"],
  afyonkarahisar: ["merkez", "bolvadin", "cay", "cobanlar", "dazkiri", "dinar", "emirdag", "evciler", "hocalar", "ihsaniye", "iscehisar", "kiziloren", "sandikli", "sinanpasa", "suhut", "sultandagi"],
  agri: ["merkez", "diyadin", "dogubayazit", "eleskirt", "hamur", "patnos", "taslicay", "tutak"],
  aksaray: ["merkez", "agackoy", "eskil", "gulagac", "guliesren", "ortakoy", "sariyahsi", "sultanhani"],
  amasya: ["merkez", "göynücek", "gümüşhacıköy", "hamamözü", "merzifon", "suluova", "taşova"],
  ankara: ["cankaya", "kecioren", "mamak", "yenimahalle", "etimesgut", "sincan", "altindag", "pursaklar", "golbasi", "polatli", "haymana", "beypazari", "nallihan", "cubuk", "kazan", "akyurt", "elmadağ", "güdül", "kalecik", "kizilcahamam", "şereflikoçhisar", "ayaş", "bala", "camlidere", "evren", "güdül", "kahramankazan"],
  antalya: ["muratpasa", "kepez", "konyaalti", "alanya", "manavgat", "serik", "kas", "kemer", "finike", "gazipaşa", "gündoğmuş", "ibradı", "kale", "kumluca", "akseki", "aksu", "dosemealtı", "elmalı"],
  ardahan: ["merkez", "cildir", "damal", "gole", "hanak", "posof"],
  artvin: ["merkez", "ardanuc", "arhavi", "borcka", "hopa", "murgul", "savsat", "yusufeli"],
  aydin: ["efeler", "nazilli", "kusadasi", "didim", "soke", "incirliova", "germencik", "bozdogan", "buharkent", "cine", "karacasu", "karpuzlu", "kocarli", "kuyucak", "sultanhisar", "yenipazar"],
  balikesir: ["altieylul", "karesi", "bandirma", "edremit", "ayvalik", "bigadic", "burhaniye", "dursunbey", "gomec", "gonen", "havran", "ıvrindi", "kepsut", "manyas", "marmara", "sakarya", "sindirgi", "susurluk"],
  bartin: ["merkez", "amasra", "kurucasile", "ulus"],
  batman: ["merkez", "beşiri", "gercus", "hasankeyf", "kozluk", "sason"],
  bayburt: ["merkez", "aydintepe", "demirozu"],
  bilecik: ["merkez", "bozuyuk", "golpazari", "inhisar", "osmaneli", "pazaryeri", "sogut", "yenipazar"],
  bingol: ["merkez", "adakli", "genc", "karliova", "kigi", "solhan", "yayladere", "yedisu"],
  bitlis: ["merkez", "adilcevaz", "ahlat", "guroymak", "hizan", "mutki", "tatvan"],
  bolu: ["merkez", "dörtdivan", "gerede", "goynuk", "kibriscik", "mengen", "mudurnu", "seben", "yeniçağa"],
  burdur: ["merkez", "aglasiun", "altinyayla", "bucak", "cavdir", "celtikci", "golhisar", "karamanli", "kemer", "tefenni", "yesilova"],
  bursa: ["nilufer", "osmangazi", "yildirim", "inegol", "gemlik", "mudanya", "gursu", "kestel", "mustafakemalpasa", "büyükorhan", "harmancik", "iznik", "karacabey", "keles", "orhaneli", "orhangazi", "yenisehir"],
  canakkale: ["merkez", "ayvacik", "bayramic", "biga", "bozcaada", "can", "eceabat", "ezine", "gelibolu", "gokceada", "lapseki", "yenice"],
  cankiri: ["merkez", "atkaracalar", "bayramoren", "cerkes", "eldivan", "ilgaz", "kizilirmak", "korgun", "kurşunlu", "orta", "şabanözü", "yaprakli"],
  corum: ["merkez", "alaca", "bayat", "bogazkale", "dodurga", "iskilip", "kargi", "lacin", "mecitözü", "oguzlar", "ortakoy", "osmancik", "sungurlu", "ugurludag"],
  denizli: ["pamukkale", "merkezefendi", "buldan", "civril", "tavas", "acipayam", "babadag", "baklan", "bekilli", "beyagac", "bozkurt", "cameli", "cardak", "guney", "honaz", "kale", "saraykoy", "serinhisar"],
  diyarbakir: ["baglar", "kayapinar", "yenisehir", "sur", "ergani", "bismil", "cermik", "cinar", "cungus", "dicle", "egil", "eğil", "hani", "hazro", "kulp", "lice", "silvan"],
  duzce: ["merkez", "akcakoca", "cumayeri", "cilimli", "golyaka", "gumusova", "kaynasli", "yigilca"],
  edirne: ["merkez", "enez", "havsa", "ipsala", "kesan", "lalapasa", "meric", "suloglu", "uzunkopru"],
  elazig: ["merkez", "agin", "aricak", "baskil", "karakocan", "keban", "kovancilar", "maden", "palu", "sivrice"],
  erzincan: ["merkez", "cayirli", "ilic", "kemah", "kemaliye", "otlukbeli", "refahiye", "tercan", "üzümlü"],
  erzurum: ["yakutiye", "aziziye", "palandoken", "oltu", "horasan", "askale", "cat", "hinis", "ispir", "karayazi", "köprüköy", "narman", "olur", "pazaryolu", "senkaya", "tekman", "tortum", "uzundere"],
  eskisehir: ["tepebaşı", "odunpazari", "alpu", "beylikova", "cihanbeyli", "gursu", "han", "inonu", "mahmudiye", "mihalgazi", "mihalıccık", "saricakaya", "seyitgazi", "sivrihisar"],
  gaziantep: ["sahinbey", "sehitkamil", "islahiye", "nizip", "oguzeli", "nurdagi", "araban", "karkamis", "yavuzeli"],
  giresun: ["merkez", "alucra", "bulancak", "camoluk", "çamoluk", "dereli", "dogankent", "espiye", "eynesil", "gorele", "guce", "kesap", "piraziz", "sebinkarahisar", "tirebolu", "yaglidere"],
  gumushane: ["merkez", "kelkit", "kose", "kurtun", "siran", "torul"],
  hakkari: ["merkez", "cukurca", "semdinli", "yuksekova"],
  hatay: ["antakya", "iskenderun", "dortyol", "reyhanli", "kirikhan", "altınözü", "belen", "dörtyol", "erzin", "hassa", "kumlu", "mandacı", "payas", "samandağ", "yayladağı"],
  igdir: ["merkez", "aralik", "karakoyunlu", "tuzluca"],
  isparta: ["merkez", "aksu", "atabey", "egirdir", "gelendost", "gonen", "keciborlu", "senirkent", "sarkikaraagac", "sutculer", "uluborlu", "yalvac", "yenisarbademli"],
  istanbul: ["kadikoy", "besiktas", "sisli", "fatih", "uskudar", "maltepe", "pendik", "umraniye", "bagcilar", "bahcelievler", "beyoglu", "sariyer", "eyup", "gaziosmanpasa", "gungoren", "kagithane", "kartal", "kucukcekmece", "sultanbeyli", "tuzla", "avcilar", "bayrampasa", "buyukcekmece", "catalca", "cekmekoy", "esenler", "esenyurt", "gungoren", "sile", "silivri", "sultanbeyli", "sultangazi", "zeytinburnu", "adalar", "arnavutkoy", "atasehir", "basaksehir", "bayrampasa", "beykoz", "beylikduzu"],
  izmir: ["konak", "karsiyaka", "bornova", "buca", "cigli", "narlidere", "gaziemir", "bayrakli", "cesme", "aliaga", "balcova", "bayindir", "bergama", "beydağ", "dikili", "foca", "guzelbahce", "karaburun", "kemalpasa", "kinik", "kiraz", "menderes", "menemen", "odemis", "seferihisar", "selcuk", "tire", "torbali", "urla"],
  kahramanmaras: ["dulkadiroglü", "onikişubat", "afsin", "andirin", "caglayancerit", "ekinozu", "elbistan", "goksun", "nurhak", "pazarcik", "turkoglu"],
  karabuk: ["merkez", "eflani", "eskipazar", "ovacik", "safranbolu", "yenice"],
  karaman: ["merkez", "ayranci", "basyayla", "ermenek", "kazimkarabekir", "sarıveliler"],
  kars: ["merkez", "akyaka", "arpaçay", "digor", "kagizman", "sarikamis", "selim", "susuz"],
  kastamonu: ["merkez", "abana", "agli", "araç", "asya", "atkaracalar", "azdavay", "bozkurt", "cide", "çatalzeytin", "daday", "devrekani", "doganyurt", "hanönü", "ihsangazi", "inebolu", "kure", "pinarbaşı", "seydiler", "smpiyonlar", "taşköprü", "tosya"],
  kayseri: ["melikgazi", "kocasinan", "talas", "develi", "yahyali", "akkisla", "bünyan", "felahiye", "hacilar", "incesu", "özvatan", "pinarbaşı", "sariz", "tomarza", "yesilhisar"],
  kilis: ["merkez", "elbeyli", "musabeyli", "polateli"],
  kirikkale: ["merkez", "bahsili", "balişeyh", "celebi", "delice", "karakecili", "keskin", "sulakyurt", "yahsihan"],
  kirklareli: ["merkez", "babaeski", "demirkoy", "kofcaz", "luleburgaz", "pehlivankoy", "pinarhisar", "vize"],
  kirsehir: ["merkez", "akcakent", "akpinar", "boztepe", "cicekdagi", "kaman", "mucur"],
  kocaeli: ["izmit", "gebze", "golcuk", "darica", "derince", "basiskele", "çayirova", "dilovasi", "kandira", "karamursel", "kartepe", "körfez"],
  konya: ["selcuklu", "meram", "karatay", "eregli", "beysehir", "aksehir", "akoren", "altinekin", "beysehir", "bozkir", "cihanbeyli", "cumra", "derbent", "derebucak", "doganhisar", "emirgazi", "guneysinir", "hadim", "halkapinar", "huyuk", "ilgin", "kadinhani", "karapinar", "kulu", "sarayonu", "seydisehir", "taskent", "tuzlukçu", "yalihuyuk", "yunak"],
  kutahya: ["merkez", "altintas", "aslanapa", "cavdarhisar", "domanic", "dumlupinar", "emet", "gediz", "hisarcik", "pazarlar", "saphane", "simav", "tavsanli"],
  malatya: ["battalgazi", "yesilyurt", "akcadag", "arapgir", "arguvan", "darende", "dogansehir", "doganyol", "hekimhan", "kale", "kuluncak", "pütürge", "yazihan"],
  manisa: ["sehzadeler", "yunusemre", "akhisar", "alaşehir", "demirci", "golmarmara", "gordes", "kirkagac", "köprübaşı", "kula", "salihli", "sarigöl", "saruhanli", "selendi", "soma", "turgutlu"],
  mardin: ["artuklu", "dargeçit", "derik", "kiziltepe", "mazidagi", "midyat", "nusaybin", "omerli", "savur", "yesilli"],
  mersin: ["yenisehir", "mezitli", "toroslar", "akdeniz", "tarsus", "erdemli", "silifke", "anamur", "aydincik", "bozyazi", "camliyayla", "gülnar", "mut"],
  mugla: ["bodrum", "marmaris", "fethiye", "milas", "datca", "dalaman", "kavaklidere", "köycegiz", "ortaca", "seydikemer", "ula", "yatagan"],
  mus: ["merkez", "bulanik", "hasköy", "korkut", "malazgirt", "varto"],
  nevsehir: ["merkez", "acigol", "avanos", "derinkuyu", "göreme", "gülsehir", "hacibektaş", "kozakli", "urgup"],
  nigde: ["merkez", "altunhisar", "bor", "ciftlik", "ulukişla"],
  ordu: ["altinordu", "akkus", "aybasti", "çamaş", "çatalpinar", "çaybaşi", "fatsa", "golkoy", "gurgentepe", "ikizce", "kabaduz", "kabatas", "korgan", "kumru", "mesudiye", "perşembe", "ulubey", "unye"],
  osmaniye: ["merkez", "bahce", "düziçi", "hasanbeyli", "kadirli", "sumbas", "toprakkale"],
  rize: ["merkez", "ardeşen", "camlihemsin", "çayeli", "derepazari", "findikli", "guneysu", "hemşin", "ikizdere", "iyidere", "kalkandere", "pazar"],
  sakarya: ["adapazari", "akyazi", "arifiye", "erenler", "ferizli", "geyve", "hendek", "karapurçek", "karasu", "kaynarca", "kocaali", "pamukova", "sapanca", "serdivan", "sogutlu", "tarakli"],
  samsun: ["ilkadim", "canik", "atakum", "tekkeköy", "bafra", "carsamba", "19-mayis", "alaçam", "asarcik", "ayvacik", "havza", "kavak", "ladik", "salıpazari", "terme", "vezirkopru", "yakakent"],
  sanliurfa: ["haliliye", "eyyubiye", "karaköprü", "siverek", "bozova", "birecik", "ceylanpinar", "halfeti", "harran", "hilvan", "suruc", "viransehir"],
  siirt: ["merkez", "aydinlar", "baykan", "eruh", "kurtalan", "pervari", "sirvan"],
  sinop: ["merkez", "ayancik", "boyabat", "dikmen", "duragan", "erfelek", "gerze", "sarayduzu", "türkeli"],
  sirnak: ["merkez", "beytussebap", "cizre", "güçlükonak", "idil", "silopi", "uludere"],
  sivas: ["merkez", "akincilar", "altieyul", "divrigi", "dogansar", "gemerek", "gölova", "gurun", "hafik", "imranli", "kangal", "koyulhisar", "susehri", "saarkisla", "ulas", "yildizeli", "zara"],
  tekirdag: ["suleymanyasepasalı", "corlu", "ergene", "hayrabolu", "kapakli", "malkara", "marmara-ereglisi", "muratlı", "saray", "sarkoy"],
  tokat: ["merkez", "almus", "artova", "basciftlik", "erbaa", "niksar", "pazar", "reşadiye", "sulusaray", "turhal", "yesilyurt", "zile"],
  trabzon: ["ortahisar", "akcaabat", "arakli", "arsin", "besikduzu", "çarsibasi", "çaykara", "dernekpazari", "duzkoy", "hayrat", "koprubasi", "macka", "of", "pelitli", "suleymankoy", "tonya", "vakfikebir", "yomra"],
  tunceli: ["merkez", "çemişgezek", "hozat", "mazgirt", "nazimiye", "ovacik", "pertek", "pülümür"],
  usak: ["merkez", "banaz", "esme", "karahalli", "sivasli", "ulubey"],
  van: ["ipekyolu", "tusba", "edremit", "baskale", "caldiran", "catak", "çatak", "ercis", "gevas", "gürpinar", "muradiye", "özalp", "saray"],
  yalova: ["merkez", "altinova", "armutlu", "çiftlikkoy", "çınarcık", "termal"],
  yozgat: ["merkez", "akdagmadeni", "aydincik", "bogazliyan", "candir", "cayiralan", "cekerek", "sarikaya", "sorgun", "şefaatli", "yerköy"],
  zonguldak: ["merkez", "alapli", "çaycuma", "devrek", "eregli", "gokcebey", "kilimli", "kozlu"],
};

export const KATEGORILER = [
  { slug: "elektronik", ad: "Elektronik", emoji: "💻" },
  { slug: "emlak",      ad: "Emlak",      emoji: "🏠" },
  { slug: "arac",       ad: "Araç",       emoji: "🚗" },
  { slug: "mobilya",    ad: "Mobilya",    emoji: "🪑" },
  { slug: "giyim",      ad: "Giyim",      emoji: "👕" },
  { slug: "spor",       ad: "Spor",       emoji: "⚽" },
  { slug: "antika",     ad: "Antika",     emoji: "🏺" },
  { slug: "oyuncak",    ad: "Oyuncak",    emoji: "🧸" },
  { slug: "kitap",      ad: "Kitap",      emoji: "📚" },
  { slug: "diger",      ad: "Diğer",      emoji: "📦" },
];
